name: Link Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  link-check:
    runs-on: ubuntu-latest
    name: Link Check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Link Check
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress '**/*.md' '**/*.mdx'
          fail: true
